# Generated by Django 3.1 on 2020-08-12 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Linha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Linha')),
            ],
            options={
                'db_table': 'linha',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Parada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Parada')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
            options={
                'db_table': 'parada',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Veiculo')),
                ('model', models.CharField(max_length=50, verbose_name='modelo')),
                ('linha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.linha', verbose_name='')),
            ],
            options={
                'db_table': 'veiculo',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PosicaoVeiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.veiculo', verbose_name='')),
            ],
            options={
                'db_table': 'PosicaoVeiculo',
            },
        ),
        migrations.AddField(
            model_name='linha',
            name='paradas',
            field=models.ManyToManyField(to='api.Parada'),
        ),
    ]
